### ISSUE TITLE
Add New Project: Solidblocks RDS PostgreSQL 

### ISSUE THREAD

**Issue by pellepelster** [hetznercloud/awesome-hcloud#100]
### Project Name

Solidblocks RDS PostgreSQL 

### Description

A containerized PostgreSQL database with all batteries included backup solution powered by pgBackRest

### Link

https://registry.terraform.io/modules/pellepelster/solidblocks-rds-postgresql/hcloud/latest

### Type

Integration

### Language

HCL

**Comment by apricote** [comment]
Added in https://github.com/hetznercloud/awesome-hcloud/commit/170a31d8682bce0d06f016d63c6784965aaf2388
