### ISSUE TITLE
Add New Project: hetzner-dyndns

### ISSUE THREAD

**Issue by marvinruder** [hetznercloud/awesome-hcloud#103]
### Project Name

hetzner-dyndns

### Description

A proxy server for updating DNS records on Hetzner DNS using the DynDNS protocol

### Link

https://github.com/marvinruder/hetzner-dyndns

### Type

Integration

### Language

Go

### Further Comments

Also available as Docker container from https://hub.docker.com/r/marvinruder/hetzner-dyndns.

**Comment by apricote** [comment]
Added in https://github.com/hetznercloud/awesome-hcloud/commit/98b0aac643323c8e68749082c893621d83acf55c :rocket:
