### ISSUE TITLE
Please consider adding TestFlows GitHub Hetzner Runners project to the list

### ISSUE THREAD

**Issue by vzakaznikov** [hetznercloud/awesome-hcloud#104]
### Project Name

TestFlows GitHub Hetzner Runners

### Description

Autoscaling GitHub Actions self-hosted runners using Hetzner Cloud

### Link

https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners

### Type

Tool

### Language

Python

### Further Comments

Please consider adding the https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners project to the list that allows autoscaling GitHub Actions self-hosted runners using Hetzner Cloud. Used in https://github.com/altinity/clickhouse-regression.

**Comment by apricote** [comment]
That looks truly awesome! 

I have added it to our CMS and it will be published in max 1 hour.

**Comment by vzakaznikov** [comment]
Thank you @apricote!
