### ISSUE TITLE
Add New Project: grafana-hcloud-datasource

### ISSUE THREAD

**Issue by apricote** [hetznercloud/awesome-hcloud#106]
### Project Name

grafana-hcloud-datasource

### Description

Metrics for your Hetzner Cloud Servers and Load Balancers in Grafana. 

### Link

https://github.com/apricote/grafana-hcloud-datasource

### Type

Integration

### Language

Go

**Comment by apricote** [comment]
@jooola Can you take a look? I do not feel comfortable reviewing and adding my own tool to the list.

**Comment by jooola** [comment]
Solved in 2ae3146c0da25a0afd02ea112a3e43198e2dfbd9
