### ISSUE TITLE
Add New Project: certmaster

### ISSUE THREAD

**Issue by poundifdef** [hetznercloud/awesome-hcloud#108]
### Project Name

certmaster

### Description

certmaster automatically creates Let's Encrypt certificates and uploads them to Hetzner load balancers

### Link

https://github.com/poundifdef/certmaster

### Type

Tool

### Language

Go

### Further Comments

This is useful when Hetzner can't automatically manage your certs, for example, if you use a different DNS provider.

**Comment by apricote** [comment]
Very nice! Saw it on Reddit and had it on my list to add it here today :)

One thing I noticed while checking out the project: It still uses `hcloud-go` v1, which is deprecated and can start breaking on 32-bit systems at any moment.

- Announcement: https://github.com/hetznercloud/hcloud-go/issues/263
- Migration Guide: https://github.com/hetznercloud/hcloud-go/blob/main/README.md#from-v1-to-v2

**Comment by apricote** [comment]
Added in https://github.com/hetznercloud/awesome-hcloud/commit/8060a8ef5c84fe6fee4de43c5e9cd3a37ea8ea7f

**Comment by poundifdef** [comment]
@apricote Thanks for approving this! I appreciate the heads up for v2, I've just updated the code to use that instead.
