### ISSUE TITLE
Add New Project: hetznerdns terraform provider

### ISSUE THREAD

**Issue by jkroepke** [hetznercloud/awesome-hcloud#111]
### Project Name

hetznerdns

### Description

A Terraform provider that helps you automate management of DNS zones and records at Hetzner DNS.

### Link

https://registry.terraform.io/providers/germanbrew/hetznerdns/latest/docs

### Type

Integration

### Language

HCL

### Further Comments

We have recently forked and modernize the Terraform provider. Strictly, Hetzner DNS and Hetzner Cloud are 2 different projects, but I see also some Hetzner DNS products here.

**Comment by jooola** [comment]
Hey @jkroepke 

I've added the project to our CMS, it should soon show up in the list.

Thanks!
