### ISSUE TITLE
hetzner-node-pool - Terraform module to easily create VMs in the Hetzner Cloud and groups them in pools for easy scaling

### ISSUE THREAD

**Issue by hegerdes** [hetznercloud/awesome-hcloud#112]
### Project Name

hetzner-node-pool

### Description

hetzner-node-pool - Terraform module to easily create VMs in the Hetzner Cloud and groups them in pools for easy scaling

### Link

https://registry.terraform.io/modules/hegerdes/hetzner-node-pool/hcloud/latest

### Type

Library

### Language

HCL

### Further Comments

The module groups common hcloud Terraform resources into one modules. This allows easy scaling.

Features: 
 * Ensuring placement groups are set
 * Public & Private IPs
 * Easy usage of snapshots
 * Easy scaling
 * Support auto generated and own VM names
 * Support for Cloud-Init 
 * Support for optional disks

Expensive examples on [GitHub](https://github.com/hegerdes/terraform-hcloud-hetzner-node-pool/tree/main/examples/complete) and also linked on [registry.terraform.io](https://registry.terraform.io/modules/hegerdes/hetzner-node-pool/hcloud/latest/examples/complete)

**Comment by jooola** [comment]
Thanks for the submission, I added your module to our internal CMS, it will be published to this list soon.
