### ISSUE TITLE
Add New Project: ServerManagerBot

### ISSUE THREAD

**Issue by erfjab** [hetznercloud/awesome-hcloud#114]
### Project Name

ServerManagerBot

### Description

ServerManagerBot is a Telegram bot for managing Hetzner servers. It allows admins to control server actions.

### Link

https://github.com/erfjab/ServerManagerBot

### Type

Tool

### Language

Python

### Further Comments

Hello and thank you for your efforts, soon more features will be added.

**Comment by jooola** [comment]
Hey :wave:  I have added your project to our internal awesome list, it will soon be published on GitHub.
