### ISSUE TITLE
Add New Project: zfs-hetzner-vm

### ISSUE THREAD

**Issue by LenzGr** [hetznercloud/awesome-hcloud#115]
### Project Name

zfs-hetzner-vm

### Description

Script to install Debian 10, 11, 12 and Ubuntu 18, 20, 22 LTS with ZFS root on Hetzner VPS

### Link

https://github.com/terem42/zfs-hetzner-vm

### Type

Tool

### Language

Bash

**Comment by jooola** [comment]
Hey 👋 I have added your project to our internal awesome list, it will soon be published on GitHub.
