### ISSUE TITLE
Add New Project: hcloud-java

### ISSUE THREAD

**Issue by CubitsDev** [hetznercloud/awesome-hcloud#116]
### Project Name

hcloud-java

### Description

hcloud-java is a fully tested and easy to use Java API Integration. It follows an Observer Pattern and focuses on minimal dependency bloat

### Link

https://github.com/CubitsDev/hcloud-java

### Type

Library

### Language

Java

### Further Comments

The library is still in development, but I'm hoping to release a pre-release version in the next few weeks. This library is a slightly different approach, where users update a local object and those changes are pushed to the API by the library. It also focuses on having **full** test coverage and minimal extra dependencies, opting to use built in JDK features where possible

**Comment by jooola** [comment]
Hey 👋 I have added your project to our internal awesome list, it will soon be published on GitHub.
