### ISSUE TITLE
Remove my deprecated hcloud-csi-driver

### ISSUE THREAD

**Issue by apricote** [hetznercloud/awesome-hcloud#36]
My [CSI Driver](https://github.com/apricote/hcloud-csi-driver) is deprecated in favor of the official driver. We should not recommend the usage of this driver for any new deployments.

You can either tag it as `deprecated` or remove it altogether from the list.

**Comment by LKaemmerling** [comment]
I have marked it with 1311101e295ee09c90dae307c3ae8b34baf64e06 as `deprecated` we will remove it in a couple of months.

**Comment by LKaemmerling** [comment]
I removed the deprecated CSI driver with 98c33f5192935584b458f3f5ba1b9f1b52f59e7f
