### ISSUE TITLE
Why vagrant-hetznercloud plugin have removed?

### ISSUE THREAD

**Issue by atomlab** [hetznercloud/awesome-hcloud#37]
1. Add vagrant-hetznercloud #7  on 8 Mar 2018
2. It removed by commit  https://github.com/hetznercloud/awesome-hcloud/commit/136670d7d1e2a9145bd10e8896001c33394e8c32#diff-04c6e90faac2675aa89e2176d2eec7d8L91 on 30 Nov 2018 

I used this module yesterday, it works fine.

**Comment by LKaemmerling** [comment]
This was removed by error. I readded it with: 1b50d62fe47dd6c80acfde50a32876cd894c8e9e Thank you for the notice!
