### ISSUE TITLE
Single node K8s provisioning tool

### ISSUE THREAD

**Issue by jerger** [hetznercloud/awesome-hcloud#38]
Hi,

we've created a provisioning tool for Single node K8s:
https://github.com/DomainDrivenArchitecture/dda-k8s-crate

It is
* cheap - we use this module to get even for low traffic apps the full k8s feeling on simple & cheap hetzner servers.
* secure - no ports left open, k8s interaction & dashboard is ssh tunneled
* complete - we integrated already dashboard, flannel, metallb, letsencrypt & applications

Our setup uses aws-route53 for dns management & hetzner-cloud for server-creation.

Interested in listing us ?

BR, Michael

**Comment by LKaemmerling** [comment]
Hey @jerger,

the tool was added with 5224f05cedf19bdb55e7991c9a8d9b30f2f28376. Thank you!
