### ISSUE TITLE
Helm Chart for hcloud-cloud-controller-manager.

### ISSUE THREAD

**Issue by MatthiasLohr** [hetznercloud/awesome-hcloud#43]
Hi,

as discussed in https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/65, I created a Open Source Helm Chart for easy installation of the hcloud-cloud-controller-manager in a Hetzner Cloud based Kubernetes Cluster. I would like to ask if you would kindly add this to the project list.

  * Project: https://gitlab.com/MatthiasLohr/hcloud-cloud-controller-manager-helm-chart
  * Helm Chart on Helm Hub: https://hub.helm.sh/charts/mlohr/hcloud-cloud-controller-manager
  * Helm Chart on Artifact Hub: https://artifacthub.io/packages/helm/mlohr/hcloud-cloud-controller-manager

Thank you very much!

Best regards
Matthias Lohr

**Comment by LKaemmerling** [comment]
Hey @MatthiasLohr,

thank you! I have added it with 3f8f0ba73b70701ab2ac5b68e313e0e9957653e8.
