### ISSUE TITLE
hcloud API bindings for Rust

### ISSUE THREAD

**Issue by HenningHolmDE** [hetznercloud/awesome-hcloud#46]
Thanks for the great work!

Over the last months, I worked on a hcloud implementation for the Rust programming language. I would be happy if you would add the project to the list.

My project on GitHub: https://github.com/HenningHolmDE/hcloud-rust/
Rust crate on crates.io: https://crates.io/crates/hcloud
Documentation on docs.rs: https://docs.rs/hcloud/latest/hcloud/

**Comment by LKaemmerling** [comment]
Thank you! I added it with 96a73c25069ad1b0e0b3e1eca476402ed1758eec
