### ISSUE TITLE
libcluster clustering strategy using Hetzner Cloud API (Elixir)

### ISSUE THREAD

**Issue by EightSQ** [hetznercloud/awesome-hcloud#48]
I built a clustering strategy utilizing label selectors on the Hetzner Cloud API for the [libcluster](https://github.com/bitwalker/libcluster) package providing automatic Erlang/Elixir cluster formation.

repository: [https://github.com/EightSQ/libcluster_hcloud]()
hex package page: [https://hex.pm/packages/libcluster_hcloud]()
hexdocs: [https://hexdocs.pm/libcluster_hcloud/readme.html]()

**Comment by LKaemmerling** [comment]
Thank you! I added it with 2b2de12.
