### ISSUE TITLE
OpenAPI representation of hcloud API

### ISSUE THREAD

**Issue by MaximilianKoestler** [hetznercloud/awesome-hcloud#49]
To allow faster integration into different programming languages and frameworks, I created semi-automatic tooling to generate an OpenAPI specification document from the HTML documentation at https://docs.hetzner.cloud/.

[OpenAPI](https://swagger.io/specification/) is a separate project that defines a standard for machine-readable representation of APIs. My repository contains the [generated specification document](https://github.com/MaximilianKoestler/hcloud-openapi/blob/master/openapi/hcloud.json) and scripts to update it when the documented feature set changes.

**My project on GitHub**: https://github.com/MaximilianKoestler/hcloud-openapi

The generated specification is currently being used by [hcloud-rust](https://github.com/HenningHolmDE/hcloud-rust/) which was added to your collection through [this issue](https://github.com/hetznercloud/awesome-hcloud/issues/46).

By the way: I have no Idea which category this specification document/my repository fits in 😃

**Comment by LKaemmerling** [comment]
Hey @MaximilianKoestler,

we are currently working on an OpenAPI Spec representation of our API. It is still WIP (we launched it with our overhauled docs right before Load Balancers GA) but it contains already all of our resources, you can find it here: https://docs.hetzner.cloud/spec.json (URL is still subject to change).  Therefore i would recommend waiting for/using our First-Party Open API Docs/Spec.


cc @m-sec

**Comment by MaximilianKoestler** [comment]
@LKaemmerling thanks for the information, I am looking forward to the official OpenAPI spec.

I have noticed that your document currently has no `components` section with schemas for shared API objects (such as prices, locations, etc...). Can you confirm that this is going to change? If not it will be much more difficult to generate well usable API implementations from that spec.

**Comment by m-sec** [comment]
Hi @MaximilianKoestler,
thanks for your feedback. We just migrated to Open API and started with a minimal set to render our docs from it. The Spec itself is currently work in progress and we are looking into which features of OAS3 we want to use. 
But I can already tell, that `components` is a thing we are going to implement soon.
