### ISSUE TITLE
Cloud API: user_data for enable_rescue action needed

### ISSUE THREAD

**Issue by selfscrum** [hetznercloud/awesome-hcloud#54]
Hi , is this the wish list place for Hetzner Cloud Service enhancements? I hope so, since I have an improvement request for your otherwise great product.

When going to rescue mode, I can install other software than the orginal OS to have a more dynamic approach than mounting precreated ISOs. I would love to automate that process with terraform or ansible, so I want to be able to inject a setup script that donwload e.g a rooter software, configures it and reboots without further manual steps.

Any plans for this? Would be great, thanks!

**Comment by LKaemmerling** [comment]
The rescue system is mostly intended to allow you "fixing" your server when you misconfigured something, or to connect to it and install a custom system. The rescue system is as small as possible and therefore doesn't have cloud-init installed. The rescue system also is the same as on the dedicated servers where cloud-init isn't available. 

I will pass your feature request to our rescue-system team..

**Comment by selfscrum** [comment]
Thanks. Meanwhile I built an alternative with Terraform mechanisms, which works actually pretty well. See [here](https://registry.terraform.io/modules/selfscrum/routeros-router/hcloud/latest) for an example.

**Comment by LKaemmerling** [comment]
Okay great, i will close the issue then. Thank you!
