### ISSUE TITLE
RouterOS module for the projct list

### ISSUE THREAD

**Issue by selfscrum** [hetznercloud/awesome-hcloud#57]
Hi 

I built a RouterOS router module which automatically configures the router to a safe start mode, based on a Hetzner server. Can you please add it to the project list?

* https://registry.terraform.io/modules/selfscrum/routeros-router/hcloud/latest
* https://registry.terraform.io/modules/selfscrum/routeros-router-configuration/hcloud/latest

Thanks!
-- selfscrum

**Comment by LKaemmerling** [comment]
Hey @selfscrum,

thank you! I added both with 2ed726a and 8ddd1b7.
