### ISSUE TITLE
Terraform Module for the Hetzner Container Storage Interface Driver

### ISSUE THREAD

**Issue by colinwilson** [hetznercloud/awesome-hcloud#58]
Hi,

I've created an open source Terraform module for deploying the [Hetzner Container Storage Interface driver](https://github.com/hetznercloud/csi-driver) on Kubernetes clusters running in Hetzner Cloud. It'd be great if you could add this to the project list?

* GitHub Repo: https://github.com/colinwilson/terraform-kubernetes-hcloud-csi-driver
* Terraform Registry: https://registry.terraform.io/modules/colinwilson/hcloud-csi-driver/kubernetes/latest

Many thanks

Colin.

**Comment by LKaemmerling** [comment]
Hey @colinwilson,

thank you! I added it with 54d6a60.
