### ISSUE TITLE
Terraform Module for the Hetzner Cloud Controller Manager

### ISSUE THREAD

**Issue by colinwilson** [hetznercloud/awesome-hcloud#59]
Hi,

I've created an open source Terraform module for deploying the [Hetzner Cloud Controller Manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager) on Kubernetes clusters running in Hetzner Cloud. I ask if you could kindly add this to the project list?

* GitHub Repo: https://github.com/colinwilson/terraform-kubernetes-hcloud-controller-manager
* Terraform Registry: https://registry.terraform.io/modules/colinwilson/hcloud-controller-manager/kubernetes/latest

Many thanks

Colin.

**Comment by LKaemmerling** [comment]
Hey @colinwilson,

thank you! I added it with beffe78.
