### ISSUE TITLE
Telegram bot for managing Hetzner cloud servers

### ISSUE THREAD

**Issue by Navid2zp** [hetznercloud/awesome-hcloud#60]
Hello,

I created a telegram bot for listing and managing cloud servers. You can do reset, reboot, power off, reset password and etc.

- Repo: https://github.com/Navid2zp/hcloud-tg
- Docker: https://hub.docker.com/r/navid2zp/hcloud-tg

Thanks

**Comment by LKaemmerling** [comment]
Thank you! I added it with fed96ee.
