### ISSUE TITLE
Please consider adding my Terraform module to this project

### ISSUE THREAD

**Issue by wszychta** [hetznercloud/awesome-hcloud#69]
Hello,

I have created terraform module for user-data injection in terraform. You can find it [here](https://github.com/wszychta/terraform-module.hcloud-user-data). If you believe that this module will help other people then please add it to this project.

**Comment by apricote** [comment]
Hey @wszychta,

sorry for the far too long delay. I have added your project to our CMS and it should be published in the next 15 minutes.
