### ISSUE TITLE
Hetzner Rescaler CLI

### ISSUE THREAD

**Issue by enodari** [hetznercloud/awesome-hcloud#77]
Hi,

I found an awesome CLI tool to rescale an Hetzner server to optimize your budget spending:
https://github.com/jonamat/hetzner-rescaler

Interested in listing?

Thanks, Edoardo

**Comment by LKaemmerling** [comment]
Hey @enodari,

thank you, this was added with commit 94a930f.

**Comment by enodari** [comment]
Thanks!
