### ISSUE TITLE
Releasing the OpenAPI Specs

### ISSUE THREAD

**Issue by MarianSWA** [hetznercloud/awesome-hcloud#85]
We are considering switching to Hetzner, but we would like access to the API OpenApi specs as many tools (including our own) are already providing integration with OpenApi. This is an important consideration when choosing a cloud provider.

From what I see in https://docs.hetzner.cloud/ it seems that the specs are already well defined, it's just a matter of releasing the json or yaml. Is there any chance you could make it public? 😄

**Comment by apricote** [comment]
Hey @MarianSWA,

our OpenAPI spec is published at https://docs.hetzner.cloud/spec.json but we do not provide any guarantees about the format or the specific path, so use at your own risk ;)

**Comment by MarianSWA** [comment]
Thanks @apricote I'll give it a try :)
