### ISSUE TITLE
Request to add link to Twingate CLI tool

### ISSUE THREAD

**Issue by emrul** [hetznercloud/awesome-hcloud#88]
The Twingate CLI tool `tg` now supports deployment to Hetzner Cloud, allowing users to setup a more secure alternative to a VPN. Under the hood it calls out to the Hetzner `hcloud` CLI.

Link to tool here: https://github.com/twingate-labs/tg-cli
YouTube video showing example usage scenario here: https://www.youtube.com/watch?v=kwRa22hctC4

Many thanks!

**Comment by apricote** [comment]
Hey @emrul,

sorry for the delay. I have added this to our CMS and it will show up in the next 15 minutes in the awesome list.

**Comment by emrul** [comment]
Thank you @apricote - much appreciated!!
