### ISSUE TITLE
Hetzner-k3s

### ISSUE THREAD

**Issue by janosmiko** [hetznercloud/awesome-hcloud#90]
Hi,

I created a [PR](https://github.com/hetznercloud/awesome-hcloud/pull/89) to add my latest [project](https://github.com/janosmiko/hetzner-k3s) to the list. I hope you find it useful.

It's a CLI utility (written in Go) that is able to create lightweight Kubernetes (k3s) clusters in Hetzner in minutes.

**Comment by apricote** [comment]
Added in 961b39057d7fe97d06fb69389572a507997a380e
